name: Issue Close Require

on:
  workflow_dispatch:
jobs:
  close-issues:
    runs-on: ubuntu-22.04
    steps:
      - name: missing demo
        uses: actions-cool/issues-helper@v2.2.1
        with:
          actions: close-issues
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: missing demo
          inactive-day: 3
